package lcagent

import (
	"encoding/json"
	"fmt"
	"strings"

	"lcroom/internal/lcagent/modeladapter"
	"lcroom/internal/lcagent/tools"
)

const (
	finalHandoffTranscriptMaxChars = 48000
	finalHandoffAssistantMaxChars  = 2000
	finalHandoffArgsMaxChars       = 900
	finalHandoffToolOutputChars    = 1400
	finalHandoffRecentOutputChars  = 3200
	finalHandoffRecentToolResults  = 6

	loopCompactionCharThreshold   = 70000
	loopCompactionTranscriptChars = 30000
	loopCompactionAssistantChars  = 1600
	loopCompactionArgsChars       = 700
	loopCompactionToolOutputChars = 900
	loopCompactionRecentChars     = 2200
	loopCompactionRecentResults   = 4

	loopCompactedContextPrefix = "Compacted session context generated by the harness."
)

type finalHandoffCompactionStats struct {
	OriginalMessages  int `json:"original_messages"`
	CompactedMessages int `json:"compacted_messages"`
	OriginalChars     int `json:"original_chars"`
	CompactedChars    int `json:"compacted_chars"`
	ToolResults       int `json:"tool_results"`
	ReadLedgerFiles   int `json:"read_ledger_files,omitempty"`
	ReadLedgerRanges  int `json:"read_ledger_ranges,omitempty"`
}

type compactToolCall struct {
	Name string
	Args string
}

type openRouterCompactionOptions struct {
	TranscriptMaxChars int
	AssistantMaxChars  int
	ArgsMaxChars       int
	ToolOutputChars    int
	RecentOutputChars  int
	RecentToolResults  int
}

func compactOpenRouterFinalMessages(messages []modeladapter.Message, finalPrompt string) ([]modeladapter.Message, finalHandoffCompactionStats) {
	return compactOpenRouterFinalMessagesWithReadLedger(messages, finalPrompt, nil)
}

func compactOpenRouterFinalMessagesWithReadLedger(messages []modeladapter.Message, finalPrompt string, ledger *readLedger) ([]modeladapter.Message, finalHandoffCompactionStats) {
	stats := finalHandoffCompactionStats{
		OriginalMessages: len(messages),
		OriginalChars:    messagesApproxChars(messages),
	}
	stats.ReadLedgerFiles, stats.ReadLedgerRanges = ledger.Stats()
	systemContent, originalRequest, originalUserIndex := openRouterMessageAnchors(messages)
	transcript, toolResults := compactOpenRouterTranscript(messages, originalUserIndex, openRouterCompactionOptions{
		TranscriptMaxChars: finalHandoffTranscriptMaxChars,
		AssistantMaxChars:  finalHandoffAssistantMaxChars,
		ArgsMaxChars:       finalHandoffArgsMaxChars,
		ToolOutputChars:    finalHandoffToolOutputChars,
		RecentOutputChars:  finalHandoffRecentOutputChars,
		RecentToolResults:  finalHandoffRecentToolResults,
	})
	stats.ToolResults = toolResults

	var user strings.Builder
	user.WriteString("Original user request:\n")
	user.WriteString(indentBlock(strings.TrimSpace(originalRequest)))
	user.WriteString("\n\nCompact transcript of work so far. Tool outputs have been summarized to keep the final handoff small:\n")
	user.WriteString(indentBlock(transcript))
	if ledgerText := ledger.Format(readLedgerMaxChars); ledgerText != "" {
		user.WriteString("\n\nRead ledger of successful read_file ranges already inspected:\n")
		user.WriteString(indentBlock(ledgerText))
	}
	user.WriteString("\n\n")
	user.WriteString(strings.TrimSpace(finalPrompt))

	compacted := []modeladapter.Message{}
	if strings.TrimSpace(systemContent) != "" {
		compacted = append(compacted, modeladapter.Message{Role: "system", Content: systemContent})
	}
	compacted = append(compacted, modeladapter.Message{Role: "user", Content: user.String()})
	stats.CompactedMessages = len(compacted)
	stats.CompactedChars = messagesApproxChars(compacted)
	return compacted, stats
}

func compactOpenRouterLoopMessages(messages []modeladapter.Message) ([]modeladapter.Message, finalHandoffCompactionStats, bool) {
	return compactOpenRouterLoopMessagesWithReadLedger(messages, nil)
}

func compactOpenRouterLoopMessagesWithReadLedger(messages []modeladapter.Message, ledger *readLedger) ([]modeladapter.Message, finalHandoffCompactionStats, bool) {
	stats := finalHandoffCompactionStats{
		OriginalMessages: len(messages),
		OriginalChars:    messagesApproxChars(messages),
	}
	if stats.OriginalChars < loopCompactionCharThreshold {
		return messages, stats, false
	}
	toolResults := countToolResultMessages(messages)
	if toolResults == 0 {
		return messages, stats, false
	}
	stats.ReadLedgerFiles, stats.ReadLedgerRanges = ledger.Stats()
	systemContent, originalRequest, originalUserIndex := openRouterMessageAnchors(messages)
	transcript, toolResults := compactOpenRouterTranscript(messages, originalUserIndex, openRouterCompactionOptions{
		TranscriptMaxChars: loopCompactionTranscriptChars,
		AssistantMaxChars:  loopCompactionAssistantChars,
		ArgsMaxChars:       loopCompactionArgsChars,
		ToolOutputChars:    loopCompactionToolOutputChars,
		RecentOutputChars:  loopCompactionRecentChars,
		RecentToolResults:  loopCompactionRecentResults,
	})
	stats.ToolResults = toolResults

	var context strings.Builder
	context.WriteString(loopCompactedContextPrefix)
	context.WriteString("\n\n")
	context.WriteString("This is not a new user request. Continue the original task using the compacted evidence below.")
	context.WriteString("\n\nTranscript summary:\n")
	context.WriteString(indentBlock(transcript))
	if ledgerText := ledger.Format(readLedgerMaxChars); ledgerText != "" {
		context.WriteString("\n\nRead ledger of successful read_file ranges already inspected:\n")
		context.WriteString(indentBlock(ledgerText))
	}
	context.WriteString("\n\nContinuation instructions:\n")
	context.WriteString("- You may call tools if more evidence is genuinely needed.\n")
	context.WriteString("- Check the read ledger before calling read_file; prefer unread adjacent ranges, search, file_outline, or module_outline when they answer the question.\n")
	context.WriteString("- Re-read an already inspected range only when exact current lines are needed for edits or verification.\n")
	context.WriteString("- When ready, call final_response exactly once.")

	compacted := []modeladapter.Message{}
	if strings.TrimSpace(systemContent) != "" {
		compacted = append(compacted, modeladapter.Message{Role: "system", Content: systemContent})
	}
	if strings.TrimSpace(originalRequest) != "" {
		compacted = append(compacted, modeladapter.Message{Role: "user", Content: originalRequest})
	}
	compacted = append(compacted, modeladapter.Message{Role: "user", Content: context.String()})
	stats.CompactedMessages = len(compacted)
	stats.CompactedChars = messagesApproxChars(compacted)
	return compacted, stats, true
}

func openRouterMessageAnchors(messages []modeladapter.Message) (string, string, int) {
	systemContent := ""
	originalRequest := ""
	originalUserIndex := -1
	for i, msg := range messages {
		if systemContent == "" && msg.Role == "system" {
			systemContent = msg.Content
			continue
		}
		if originalRequest == "" && msg.Role == "user" {
			originalRequest = msg.Content
			originalUserIndex = i
		}
	}
	return systemContent, originalRequest, originalUserIndex
}

func compactOpenRouterTranscript(messages []modeladapter.Message, originalUserIndex int, opts openRouterCompactionOptions) (string, int) {
	toolResults := countToolResultMessages(messages)
	var entries []string
	toolCalls := map[string]compactToolCall{}
	seenToolResults := 0
	for i, msg := range messages {
		if msg.Role == "system" || i == originalUserIndex {
			continue
		}
		switch msg.Role {
		case "assistant":
			if content := strings.TrimSpace(msg.Content); content != "" {
				entries = append(entries, "assistant_note:\n"+indentBlock(truncateMiddle(content, opts.AssistantMaxChars)))
			}
			for _, call := range msg.ToolCalls {
				name := strings.TrimSpace(call.Function.Name)
				if name == "" {
					name = "unknown"
				}
				args := compactRawJSON(call.Function.Arguments, opts.ArgsMaxChars)
				if call.ID != "" {
					toolCalls[call.ID] = compactToolCall{Name: name, Args: args}
				}
				entries = append(entries, fmt.Sprintf("tool_call: %s args=%s", name, args))
			}
		case "tool":
			seenToolResults++
			call := toolCalls[msg.ToolCallID]
			if call.Name == "" {
				call.Name = "unknown"
			}
			limit := opts.ToolOutputChars
			if toolResults-seenToolResults < opts.RecentToolResults {
				limit = opts.RecentOutputChars
			}
			entries = append(entries, compactToolResultEntry(call.Name, call.Args, msg.Content, limit))
		case "user":
			if content := strings.TrimSpace(msg.Content); content != "" {
				label := "user_note"
				if strings.HasPrefix(content, loopCompactedContextPrefix) {
					label = "previous_compacted_context"
				}
				entries = append(entries, label+":\n"+indentBlock(truncateMiddle(content, opts.AssistantMaxChars)))
			}
		}
	}

	transcript := strings.TrimSpace(strings.Join(entries, "\n\n"))
	if transcript == "" {
		transcript = "No compact transcript entries were available."
	}
	return truncateMiddle(transcript, opts.TranscriptMaxChars), toolResults
}

func countToolResultMessages(messages []modeladapter.Message) int {
	total := 0
	for _, msg := range messages {
		if msg.Role == "tool" {
			total++
		}
	}
	return total
}

func compactToolResultEntry(toolName, args, content string, outputLimit int) string {
	var result tools.ToolResult
	if err := json.Unmarshal([]byte(content), &result); err != nil {
		return fmt.Sprintf("tool_result: %s args=%s\n%s", toolName, args, indentBlock(truncateMiddle(strings.TrimSpace(content), outputLimit)))
	}
	status := fmt.Sprintf("tool_result: %s args=%s success=%t", toolName, args, result.Success)
	if result.Truncated {
		status += " truncated=true"
	}
	if result.Binary {
		status += " binary=true"
	}
	if result.TimedOut {
		status += " timed_out=true"
	}
	if len(result.FilesTouched) > 0 {
		status += " files_touched=" + strings.Join(result.FilesTouched, ",")
	}
	if strings.TrimSpace(result.Error) != "" {
		return status + "\nerror:\n" + indentBlock(truncateMiddle(result.Error, outputLimit))
	}
	if strings.TrimSpace(result.Output) == "" {
		return status
	}
	return status + "\noutput:\n" + indentBlock(compactToolOutput(toolName, result.Output, outputLimit))
}

func compactToolOutput(toolName, output string, limit int) string {
	output = strings.TrimSpace(strings.ReplaceAll(output, "\r\n", "\n"))
	if output == "" {
		return ""
	}
	if len(output) <= limit {
		return output
	}
	if toolName == "read_file" {
		if header, body, ok := strings.Cut(output, "\n\n"); ok {
			remaining := limit - len(header) - 64
			if remaining > 300 {
				return strings.TrimSpace(header) + "\n\n" + truncateMiddle(strings.TrimSpace(body), remaining)
			}
		}
	}
	return truncateMiddle(output, limit)
}

func compactRawJSON(raw json.RawMessage, limit int) string {
	raw = []byte(strings.TrimSpace(string(raw)))
	if len(raw) == 0 {
		return "{}"
	}
	var value any
	if err := json.Unmarshal(raw, &value); err == nil {
		if encoded, err := json.Marshal(value); err == nil {
			return truncateMiddle(string(encoded), limit)
		}
	}
	return truncateMiddle(string(raw), limit)
}

func messagesApproxChars(messages []modeladapter.Message) int {
	total := 0
	for _, msg := range messages {
		total += len(msg.Role) + len(msg.Content) + len(msg.ToolCallID)
		for _, call := range msg.ToolCalls {
			total += len(call.ID) + len(call.Type) + len(call.Function.Name) + len(call.Function.Arguments)
		}
	}
	return total
}

func indentBlock(text string) string {
	text = strings.TrimSpace(text)
	if text == "" {
		return "  none"
	}
	lines := strings.Split(text, "\n")
	for i, line := range lines {
		lines[i] = "  " + line
	}
	return strings.Join(lines, "\n")
}

func truncateMiddle(text string, limit int) string {
	text = strings.TrimSpace(text)
	if limit <= 0 || len(text) <= limit {
		return text
	}
	omission := fmt.Sprintf("\n... omitted %d chars ...\n", len(text)-limit)
	keep := limit - len(omission)
	if keep <= 0 {
		if limit < len(omission) {
			return omission[:limit]
		}
		return omission
	}
	runes := []rune(text)
	if len(runes) <= keep {
		return text
	}
	head := keep / 2
	tail := keep - head
	return strings.TrimSpace(string(runes[:head])) + omission + strings.TrimSpace(string(runes[len(runes)-tail:]))
}
