package lcagent

import (
	"encoding/json"
	"fmt"
	"strings"

	"lcroom/internal/agentcontext"
	"lcroom/internal/lcagent/modeladapter"
	"lcroom/internal/lcagent/tools"
)

const (
	finalHandoffTranscriptMaxChars = 80000
	finalHandoffAssistantMaxChars  = 2400
	finalHandoffArgsMaxChars       = 1100
	finalHandoffToolOutputChars    = 1800
	finalHandoffRecentOutputChars  = 5000
	finalHandoffRecentToolResults  = 8

	loopCompactionCharThreshold   = 200000
	loopCompactionTranscriptChars = 50000
	loopCompactionAssistantChars  = 1600
	loopCompactionArgsChars       = 800
	loopCompactionToolOutputChars = 900
	loopCompactionRecentChars     = 2500
	loopCompactionRecentResults   = 4

	loopCompactedContextPrefix = "Compacted session context generated by the harness."

	contextPackingApproxCharsPerToken     = 4
	contextPackingSmallWindowTokens       = 200000
	contextPackingLargeWindowTokens       = 1000000
	contextPackingMaxUtilizationPercent   = 80
	contextPackingMinUtilizationPercent   = 50
	contextPackingTranscriptTargetPercent = 30
	contextPackingMinTranscriptTokens     = 8000
)

type openRouterContextProfile string

const (
	openRouterContextProfileBalanced openRouterContextProfile = "balanced"
	openRouterContextProfileLarge    openRouterContextProfile = "large"
)

type finalHandoffCompactionStats struct {
	OriginalMessages  int `json:"original_messages"`
	CompactedMessages int `json:"compacted_messages"`
	OriginalChars     int `json:"original_chars"`
	CompactedChars    int `json:"compacted_chars"`
	ToolResults       int `json:"tool_results"`
	ReadLedgerFiles   int `json:"read_ledger_files,omitempty"`
	ReadLedgerRanges  int `json:"read_ledger_ranges,omitempty"`
}

type compactToolCall struct {
	Name string
	Args string
}

type openRouterCompactionOptions struct {
	TranscriptMaxChars int
	AssistantMaxChars  int
	ArgsMaxChars       int
	ToolOutputChars    int
	RecentOutputChars  int
	RecentToolResults  int
}

type openRouterContextOptions struct {
	FinalHandoffTranscriptMaxChars   int   `json:"final_handoff_transcript_max_chars"`
	FinalHandoffAssistantMaxChars    int   `json:"final_handoff_assistant_max_chars"`
	FinalHandoffArgsMaxChars         int   `json:"final_handoff_args_max_chars"`
	FinalHandoffToolOutputChars      int   `json:"final_handoff_tool_output_chars"`
	FinalHandoffRecentOutputChars    int   `json:"final_handoff_recent_output_chars"`
	FinalHandoffRecentToolResults    int   `json:"final_handoff_recent_tool_results"`
	ModelContextWindowTokens         int64 `json:"model_context_window_tokens,omitempty"`
	LoopCompactionTokenBudget        int64 `json:"loop_compaction_token_budget,omitempty"`
	LoopCompactionPackedTokenBudget  int64 `json:"loop_compaction_packed_token_budget,omitempty"`
	LoopCompactionUtilizationPercent int   `json:"loop_compaction_utilization_percent,omitempty"`
	LoopCompactionCharThreshold      int   `json:"loop_compaction_char_threshold"`
	LoopCompactionTranscriptChars    int   `json:"loop_compaction_transcript_chars"`
	LoopCompactionAssistantChars     int   `json:"loop_compaction_assistant_chars"`
	LoopCompactionArgsChars          int   `json:"loop_compaction_args_chars"`
	LoopCompactionToolOutputChars    int   `json:"loop_compaction_tool_output_chars"`
	LoopCompactionRecentChars        int   `json:"loop_compaction_recent_chars"`
	LoopCompactionRecentResults      int   `json:"loop_compaction_recent_results"`
}

func parseOpenRouterContextProfile(raw string) (openRouterContextProfile, error) {
	switch openRouterContextProfile(strings.ToLower(strings.TrimSpace(raw))) {
	case "", openRouterContextProfileBalanced:
		return openRouterContextProfileBalanced, nil
	case openRouterContextProfileLarge:
		return openRouterContextProfileLarge, nil
	default:
		return "", fmt.Errorf("unsupported context profile: %s", raw)
	}
}

func openRouterContextOptionsForProfile(profile openRouterContextProfile) openRouterContextOptions {
	opts := defaultOpenRouterContextOptions()
	switch profile {
	case openRouterContextProfileLarge:
		opts.FinalHandoffTranscriptMaxChars = 240000
		opts.FinalHandoffAssistantMaxChars = 4200
		opts.FinalHandoffArgsMaxChars = 1800
		opts.FinalHandoffToolOutputChars = 3000
		opts.FinalHandoffRecentOutputChars = 10000
		opts.FinalHandoffRecentToolResults = 14
		opts.LoopCompactionCharThreshold = 600000
		opts.LoopCompactionTranscriptChars = 240000
		opts.LoopCompactionAssistantChars = 4000
		opts.LoopCompactionArgsChars = 1800
		opts.LoopCompactionToolOutputChars = 2800
		opts.LoopCompactionRecentChars = 10000
		opts.LoopCompactionRecentResults = 12
	}
	return opts.withDefaults()
}

func openRouterContextOptionsForProfileAndModel(profile openRouterContextProfile, provider, model string) openRouterContextOptions {
	opts := openRouterContextOptionsForProfile(profile)
	budget, ok := contextPackingBudgetForModel(provider, model)
	if !ok {
		return opts
	}
	opts.ModelContextWindowTokens = budget.ModelContextWindowTokens
	opts.LoopCompactionTokenBudget = budget.CompactionTokenBudget
	opts.LoopCompactionPackedTokenBudget = budget.PackedTranscriptTokenBudget
	opts.LoopCompactionUtilizationPercent = budget.UtilizationPercent
	opts.LoopCompactionCharThreshold = tokensToApproxChars(budget.CompactionTokenBudget)
	opts.LoopCompactionTranscriptChars = tokensToApproxChars(budget.PackedTranscriptTokenBudget)
	if opts.FinalHandoffTranscriptMaxChars < opts.LoopCompactionTranscriptChars {
		opts.FinalHandoffTranscriptMaxChars = opts.LoopCompactionTranscriptChars
	}
	return opts.withDefaults()
}

// ContextCompactionApproxTokenBudget returns the approximate token budget used
// before the provider-loop context is compacted for the requested profile.
func ContextCompactionApproxTokenBudget(profile string) int64 {
	return ContextCompactionApproxTokenBudgetForModel(profile, "", "")
}

// ContextCompactionApproxTokenBudgetForModel returns the approximate token
// budget used before provider-loop context is compacted for a model. When the
// model context window is unknown, it falls back to the profile defaults.
func ContextCompactionApproxTokenBudgetForModel(profile, provider, model string) int64 {
	parsed, err := parseOpenRouterContextProfile(profile)
	if err != nil {
		parsed = openRouterContextProfileBalanced
	}
	threshold := openRouterContextOptionsForProfileAndModel(parsed, provider, model).LoopCompactionCharThreshold
	if threshold <= 0 {
		return 0
	}
	return int64((threshold + contextPackingApproxCharsPerToken - 1) / contextPackingApproxCharsPerToken)
}

type contextPackingBudget struct {
	ModelContextWindowTokens    int64
	CompactionTokenBudget       int64
	PackedTranscriptTokenBudget int64
	UtilizationPercent          int
}

func contextPackingBudgetForModel(provider, model string) (contextPackingBudget, bool) {
	window, ok := knownModelContextWindowTokens(provider, model)
	if !ok || window <= 0 {
		return contextPackingBudget{}, false
	}
	utilization := contextPackingUtilizationPercent(window)
	compactionTokens := window * int64(utilization) / 100
	if compactionTokens <= 0 {
		return contextPackingBudget{}, false
	}
	packedTokens := compactionTokens * contextPackingTranscriptTargetPercent / 100
	if packedTokens < contextPackingMinTranscriptTokens && compactionTokens > contextPackingMinTranscriptTokens {
		packedTokens = contextPackingMinTranscriptTokens
	}
	maxPackedTokens := window / 4
	if maxPackedTokens > 0 && packedTokens > maxPackedTokens {
		packedTokens = maxPackedTokens
	}
	if packedTokens >= compactionTokens {
		packedTokens = compactionTokens / 2
	}
	if packedTokens <= 0 {
		packedTokens = compactionTokens
	}
	return contextPackingBudget{
		ModelContextWindowTokens:    window,
		CompactionTokenBudget:       compactionTokens,
		PackedTranscriptTokenBudget: packedTokens,
		UtilizationPercent:          utilization,
	}, true
}

func contextPackingUtilizationPercent(windowTokens int64) int {
	switch {
	case windowTokens <= contextPackingSmallWindowTokens:
		return contextPackingMaxUtilizationPercent
	case windowTokens >= contextPackingLargeWindowTokens:
		return contextPackingMinUtilizationPercent
	default:
		span := int64(contextPackingLargeWindowTokens - contextPackingSmallWindowTokens)
		used := windowTokens - int64(contextPackingSmallWindowTokens)
		drop := int64(contextPackingMaxUtilizationPercent-contextPackingMinUtilizationPercent) * used / span
		return contextPackingMaxUtilizationPercent - int(drop)
	}
}

func knownModelContextWindowTokens(provider, model string) (int64, bool) {
	names := compactModelContextNames(provider, model)
	for _, name := range names {
		if tokens, ok := modelContextWindowHint(name); ok {
			return tokens, true
		}
		switch {
		case strings.Contains(name, "mimo-v2.5-pro"):
			return 1000000, true
		case strings.Contains(name, "mimo-v2.5"):
			return 256000, true
		case strings.Contains(name, "gpt-5.6-luna"):
			return 400000, true
		case strings.Contains(name, "gpt-5.6"):
			return 1050000, true
		case strings.Contains(name, "gpt-5.5"):
			return 400000, true
		case strings.Contains(name, "gpt-5.4") || strings.Contains(name, "gpt-5"):
			return 200000, true
		case strings.Contains(name, "kimi-k2.7-code") || strings.Contains(name, "kimi-k2.6"):
			return 256000, true
		case strings.Contains(name, "deepseek-v4") || deepSeekV4CompatibilityModelName(name):
			return 1000000, true
		case strings.Contains(name, "glm-5.1"):
			return 128000, true
		}
	}
	return 0, false
}

func deepSeekV4CompatibilityModelName(name string) bool {
	return name == "deepseek-chat" ||
		name == "deepseek-reasoner" ||
		strings.HasSuffix(name, "/deepseek-chat") ||
		strings.HasSuffix(name, "/deepseek-reasoner")
}

func compactModelContextNames(provider, model string) []string {
	provider = strings.ToLower(strings.TrimSpace(provider))
	model = strings.ToLower(strings.TrimSpace(model))
	names := []string{}
	add := func(value string) {
		value = strings.ToLower(strings.TrimSpace(value))
		if value == "" {
			return
		}
		for _, existing := range names {
			if existing == value {
				return
			}
		}
		names = append(names, value)
	}
	add(model)
	add(modeladapter.NormalizeModelForProvider(provider, model))
	if provider != "" && model != "" && !strings.HasPrefix(model, provider+"/") {
		add(provider + "/" + model)
	}
	return names
}

func modelContextWindowHint(name string) (int64, bool) {
	replacer := strings.NewReplacer("/", "-", "_", "-", ":", "-", ".", "-", " ", "-")
	for _, part := range strings.Split(replacer.Replace(strings.ToLower(strings.TrimSpace(name))), "-") {
		if len(part) < 2 {
			continue
		}
		multiplier := int64(0)
		switch part[len(part)-1] {
		case 'k':
			multiplier = 1000
		case 'm':
			multiplier = 1000000
		default:
			continue
		}
		value := int64(0)
		for _, ch := range part[:len(part)-1] {
			if ch < '0' || ch > '9' {
				value = 0
				break
			}
			value = value*10 + int64(ch-'0')
		}
		if value > 0 {
			return value * multiplier, true
		}
	}
	return 0, false
}

func tokensToApproxChars(tokens int64) int {
	if tokens <= 0 {
		return 0
	}
	chars := tokens * contextPackingApproxCharsPerToken
	if chars > int64(^uint(0)>>1) {
		return int(^uint(0) >> 1)
	}
	return int(chars)
}

func defaultOpenRouterContextOptions() openRouterContextOptions {
	return openRouterContextOptions{
		FinalHandoffTranscriptMaxChars: finalHandoffTranscriptMaxChars,
		FinalHandoffAssistantMaxChars:  finalHandoffAssistantMaxChars,
		FinalHandoffArgsMaxChars:       finalHandoffArgsMaxChars,
		FinalHandoffToolOutputChars:    finalHandoffToolOutputChars,
		FinalHandoffRecentOutputChars:  finalHandoffRecentOutputChars,
		FinalHandoffRecentToolResults:  finalHandoffRecentToolResults,
		LoopCompactionCharThreshold:    loopCompactionCharThreshold,
		LoopCompactionTranscriptChars:  loopCompactionTranscriptChars,
		LoopCompactionAssistantChars:   loopCompactionAssistantChars,
		LoopCompactionArgsChars:        loopCompactionArgsChars,
		LoopCompactionToolOutputChars:  loopCompactionToolOutputChars,
		LoopCompactionRecentChars:      loopCompactionRecentChars,
		LoopCompactionRecentResults:    loopCompactionRecentResults,
	}
}

func (opts openRouterContextOptions) withDefaults() openRouterContextOptions {
	defaults := defaultOpenRouterContextOptions()
	if opts.FinalHandoffTranscriptMaxChars <= 0 {
		opts.FinalHandoffTranscriptMaxChars = defaults.FinalHandoffTranscriptMaxChars
	}
	if opts.FinalHandoffAssistantMaxChars <= 0 {
		opts.FinalHandoffAssistantMaxChars = defaults.FinalHandoffAssistantMaxChars
	}
	if opts.FinalHandoffArgsMaxChars <= 0 {
		opts.FinalHandoffArgsMaxChars = defaults.FinalHandoffArgsMaxChars
	}
	if opts.FinalHandoffToolOutputChars <= 0 {
		opts.FinalHandoffToolOutputChars = defaults.FinalHandoffToolOutputChars
	}
	if opts.FinalHandoffRecentOutputChars <= 0 {
		opts.FinalHandoffRecentOutputChars = defaults.FinalHandoffRecentOutputChars
	}
	if opts.FinalHandoffRecentToolResults <= 0 {
		opts.FinalHandoffRecentToolResults = defaults.FinalHandoffRecentToolResults
	}
	if opts.LoopCompactionCharThreshold <= 0 {
		opts.LoopCompactionCharThreshold = defaults.LoopCompactionCharThreshold
	}
	if opts.LoopCompactionTranscriptChars <= 0 {
		opts.LoopCompactionTranscriptChars = defaults.LoopCompactionTranscriptChars
	}
	if opts.LoopCompactionAssistantChars <= 0 {
		opts.LoopCompactionAssistantChars = defaults.LoopCompactionAssistantChars
	}
	if opts.LoopCompactionArgsChars <= 0 {
		opts.LoopCompactionArgsChars = defaults.LoopCompactionArgsChars
	}
	if opts.LoopCompactionToolOutputChars <= 0 {
		opts.LoopCompactionToolOutputChars = defaults.LoopCompactionToolOutputChars
	}
	if opts.LoopCompactionRecentChars <= 0 {
		opts.LoopCompactionRecentChars = defaults.LoopCompactionRecentChars
	}
	if opts.LoopCompactionRecentResults <= 0 {
		opts.LoopCompactionRecentResults = defaults.LoopCompactionRecentResults
	}
	return opts
}

func compactOpenRouterFinalMessages(messages []modeladapter.Message, finalPrompt string) ([]modeladapter.Message, finalHandoffCompactionStats) {
	return compactOpenRouterFinalMessagesWithReadLedger(messages, finalPrompt, nil)
}

func compactOpenRouterFinalMessagesWithReadLedger(messages []modeladapter.Message, finalPrompt string, ledger *readLedger) ([]modeladapter.Message, finalHandoffCompactionStats) {
	return compactOpenRouterFinalMessagesWithOptions(messages, finalPrompt, ledger, defaultOpenRouterContextOptions())
}

func compactOpenRouterFinalMessagesWithOptions(messages []modeladapter.Message, finalPrompt string, ledger *readLedger, contextOpts openRouterContextOptions) ([]modeladapter.Message, finalHandoffCompactionStats) {
	contextOpts = contextOpts.withDefaults()
	stats := finalHandoffCompactionStats{
		OriginalMessages: len(messages),
		OriginalChars:    messagesApproxChars(messages),
	}
	stats.ReadLedgerFiles, stats.ReadLedgerRanges = ledger.Stats()
	systemContent, currentRequest, currentUserIndex := openRouterCurrentTaskMessageAnchors(messages)
	transcript, toolResults := compactOpenRouterTranscript(messages, currentUserIndex, openRouterCompactionOptions{
		TranscriptMaxChars: contextOpts.FinalHandoffTranscriptMaxChars,
		AssistantMaxChars:  contextOpts.FinalHandoffAssistantMaxChars,
		ArgsMaxChars:       contextOpts.FinalHandoffArgsMaxChars,
		ToolOutputChars:    contextOpts.FinalHandoffToolOutputChars,
		RecentOutputChars:  contextOpts.FinalHandoffRecentOutputChars,
		RecentToolResults:  contextOpts.FinalHandoffRecentToolResults,
	})
	stats.ToolResults = toolResults

	var user strings.Builder
	user.WriteString("Current user request:\n")
	user.WriteString(indentBlock(strings.TrimSpace(currentRequest)))
	user.WriteString("\n\nCompact transcript of work so far. Tool outputs have been summarized to keep the final handoff small:\n")
	user.WriteString(indentBlock(transcript))
	if ledgerText := ledger.Format(readLedgerMaxChars); ledgerText != "" {
		user.WriteString("\n\nRead ledger of successful read_file ranges already inspected:\n")
		user.WriteString(indentBlock(ledgerText))
	}
	user.WriteString("\n\n")
	user.WriteString(strings.TrimSpace(finalPrompt))

	compacted := []modeladapter.Message{}
	if strings.TrimSpace(systemContent) != "" {
		compacted = append(compacted, modeladapter.Message{Role: "system", Content: systemContent})
	}
	compacted = append(compacted, modeladapter.Message{Role: "user", Content: user.String()})
	stats.CompactedMessages = len(compacted)
	stats.CompactedChars = messagesApproxChars(compacted)
	return compacted, stats
}

func compactOpenRouterLoopMessages(messages []modeladapter.Message) ([]modeladapter.Message, finalHandoffCompactionStats, bool) {
	return compactOpenRouterLoopMessagesWithReadLedger(messages, nil)
}

func compactOpenRouterLoopMessagesWithReadLedger(messages []modeladapter.Message, ledger *readLedger) ([]modeladapter.Message, finalHandoffCompactionStats, bool) {
	return compactOpenRouterLoopMessagesWithOptions(messages, ledger, defaultOpenRouterContextOptions())
}

func compactOpenRouterLoopMessagesWithOptions(messages []modeladapter.Message, ledger *readLedger, contextOpts openRouterContextOptions) ([]modeladapter.Message, finalHandoffCompactionStats, bool) {
	contextOpts = contextOpts.withDefaults()
	stats := finalHandoffCompactionStats{
		OriginalMessages: len(messages),
		OriginalChars:    messagesApproxChars(messages),
	}
	if stats.OriginalChars < contextOpts.LoopCompactionCharThreshold {
		return messages, stats, false
	}
	stats.ReadLedgerFiles, stats.ReadLedgerRanges = ledger.Stats()
	systemContent, currentRequest, currentUserIndex := openRouterCurrentTaskMessageAnchors(messages)
	transcript, toolResults := compactOpenRouterTranscript(messages, currentUserIndex, openRouterCompactionOptions{
		TranscriptMaxChars: contextOpts.LoopCompactionTranscriptChars,
		AssistantMaxChars:  contextOpts.LoopCompactionAssistantChars,
		ArgsMaxChars:       contextOpts.LoopCompactionArgsChars,
		ToolOutputChars:    contextOpts.LoopCompactionToolOutputChars,
		RecentOutputChars:  contextOpts.LoopCompactionRecentChars,
		RecentToolResults:  contextOpts.LoopCompactionRecentResults,
	})
	stats.ToolResults = toolResults

	var context strings.Builder
	context.WriteString(loopCompactedContextPrefix)
	context.WriteString("\n\n")
	context.WriteString("This is not a new user request. Continue the latest real user request above using the compacted evidence below.")
	context.WriteString("\n\nTranscript summary:\n")
	context.WriteString(indentBlock(transcript))
	if ledgerText := ledger.Format(readLedgerMaxChars); ledgerText != "" {
		context.WriteString("\n\nRead ledger of successful read_file ranges already inspected:\n")
		context.WriteString(indentBlock(ledgerText))
	}
	context.WriteString("\n\nContinuation instructions:\n")
	context.WriteString("- You may call tools if more evidence is genuinely needed.\n")
	context.WriteString("- Check the read ledger before calling read_file; prefer repo_overview, unread adjacent ranges, search, file_outline, or module_outline when they answer the question.\n")
	context.WriteString("- Re-read an already inspected range only when exact current lines are needed for edits or verification.\n")
	context.WriteString("- When ready, call final_response exactly once.")

	compacted := []modeladapter.Message{}
	if strings.TrimSpace(systemContent) != "" {
		compacted = append(compacted, modeladapter.Message{Role: "system", Content: systemContent})
	}
	if strings.TrimSpace(currentRequest) != "" {
		compacted = append(compacted, modeladapter.Message{Role: "user", Content: currentRequest})
	}
	compacted = append(compacted, modeladapter.Message{Role: "user", Content: context.String()})
	stats.CompactedMessages = len(compacted)
	stats.CompactedChars = messagesApproxChars(compacted)
	if stats.CompactedChars >= stats.OriginalChars {
		return messages, stats, false
	}
	return compacted, stats, true
}

func openRouterCurrentTaskMessageAnchors(messages []modeladapter.Message) (string, string, int) {
	systemContent := ""
	currentRequest := ""
	currentUserIndex := -1
	for i, msg := range messages {
		if systemContent == "" && msg.Role == "system" {
			systemContent = msg.Content
			continue
		}
		if msg.Role == "user" && strings.TrimSpace(msg.Content) != "" && !isOpenRouterHarnessUserMessage(msg.Content) {
			currentRequest = msg.Content
			currentUserIndex = i
		}
	}
	if currentRequest != "" {
		return systemContent, currentRequest, currentUserIndex
	}
	for i, msg := range messages {
		if msg.Role == "user" && strings.TrimSpace(msg.Content) != "" {
			return systemContent, msg.Content, i
		}
	}
	return systemContent, "", -1
}

func isOpenRouterHarnessUserMessage(content string) bool {
	content = strings.TrimSpace(content)
	if content == "" {
		return true
	}
	for _, prefix := range []string{
		loopCompactedContextPrefix,
		openRouterProgressNotePrefix,
		"Final response feedback:",
		"Verification feedback:",
		"Patch feedback:",
		"Patch retry guidance:",
	} {
		if strings.HasPrefix(content, prefix) {
			return true
		}
	}
	return strings.Contains(content, "This is not a new user request.")
}

func compactOpenRouterTranscript(messages []modeladapter.Message, originalUserIndex int, opts openRouterCompactionOptions) (string, int) {
	toolResults := countToolResultMessages(messages)
	var entries []string
	toolCalls := map[string]compactToolCall{}
	seenToolResults := 0
	for i, msg := range messages {
		if msg.Role == "system" || i == originalUserIndex {
			continue
		}
		switch msg.Role {
		case "assistant":
			if content := strings.TrimSpace(msg.Content); content != "" {
				entries = append(entries, "assistant_note:\n"+indentBlock(truncateMiddle(content, opts.AssistantMaxChars)))
			}
			for _, call := range msg.ToolCalls {
				name := strings.TrimSpace(call.Function.Name)
				if name == "" {
					name = "unknown"
				}
				args := compactRawJSON(call.Function.Arguments, opts.ArgsMaxChars)
				if call.ID != "" {
					toolCalls[call.ID] = compactToolCall{Name: name, Args: args}
				}
				entries = append(entries, fmt.Sprintf("tool_call: %s args=%s", name, args))
			}
		case "tool":
			seenToolResults++
			call := toolCalls[msg.ToolCallID]
			if call.Name == "" {
				call.Name = "unknown"
			}
			limit := opts.ToolOutputChars
			if toolResults-seenToolResults < opts.RecentToolResults {
				limit = opts.RecentOutputChars
			}
			entries = append(entries, compactToolResultEntry(call.Name, call.Args, msg.Content, limit))
		case "user":
			if content := strings.TrimSpace(msg.Content); content != "" {
				label := "user_note"
				if strings.HasPrefix(content, loopCompactedContextPrefix) {
					label = "previous_compacted_context"
				}
				entries = append(entries, label+":\n"+indentBlock(truncateMiddle(content, opts.AssistantMaxChars)))
			}
		}
	}

	transcript := strings.TrimSpace(strings.Join(entries, "\n\n"))
	if transcript == "" {
		transcript = "No compact transcript entries were available."
	}
	return truncateMiddle(transcript, opts.TranscriptMaxChars), toolResults
}

func countToolResultMessages(messages []modeladapter.Message) int {
	total := 0
	for _, msg := range messages {
		if msg.Role == "tool" {
			total++
		}
	}
	return total
}

func compactToolResultEntry(toolName, args, content string, outputLimit int) string {
	var result tools.ToolResult
	if err := json.Unmarshal([]byte(content), &result); err != nil {
		return fmt.Sprintf("tool_result: %s args=%s\n%s", toolName, args, indentBlock(truncateMiddle(strings.TrimSpace(content), outputLimit)))
	}
	status := fmt.Sprintf("tool_result: %s args=%s success=%t", toolName, args, result.Success)
	if strings.TrimSpace(result.Command) != "" {
		status += fmt.Sprintf(" command=%q", strings.TrimSpace(result.Command))
	}
	if strings.TrimSpace(result.CWD) != "" {
		status += fmt.Sprintf(" cwd=%q", strings.TrimSpace(result.CWD))
	}
	if result.Truncated {
		status += " truncated=true"
	}
	if result.Binary {
		status += " binary=true"
	}
	if result.TimedOut {
		status += " timed_out=true"
	}
	if len(result.FilesTouched) > 0 {
		status += " files_touched=" + strings.Join(result.FilesTouched, ",")
	}
	if strings.TrimSpace(result.Error) != "" {
		return status + "\nerror:\n" + indentBlock(truncateMiddle(result.Error, outputLimit))
	}
	if strings.TrimSpace(result.Output) == "" {
		return status
	}
	return status + "\noutput:\n" + indentBlock(compactToolOutput(toolName, result, outputLimit))
}

func compactToolOutput(toolName string, result tools.ToolResult, limit int) string {
	output := result.Output
	output = strings.TrimSpace(strings.ReplaceAll(output, "\r\n", "\n"))
	if output == "" {
		return ""
	}
	if toolName == "run_command" {
		if compacted, ok := compactCommandOutput(result, limit); ok {
			return compacted
		}
	}
	if len(output) <= limit {
		return output
	}
	if toolName == "read_file" {
		if header, body, ok := strings.Cut(output, "\n\n"); ok {
			remaining := limit - len(header) - 64
			if remaining > 300 {
				return strings.TrimSpace(header) + "\n\n" + truncateMiddle(strings.TrimSpace(body), remaining)
			}
		}
	}
	return truncateMiddle(output, limit)
}

func compactCommandOutput(result tools.ToolResult, limit int) (string, bool) {
	output := strings.TrimSpace(strings.ReplaceAll(result.Output, "\r\n", "\n"))
	if output == "" {
		return "", false
	}
	command := strings.TrimSpace(result.Command)
	if commandLooksLikeGitStatus(command) {
		return compactGitStatusOutput(result, limit), true
	}
	if !result.Truncated && !commandOutputHasNoisyPath(output) {
		return "", false
	}
	var lines []string
	lines = append(lines, "command output compacted")
	if result.Truncated {
		lines = append(lines, "truncated: true")
	}
	if artifact := strings.TrimSpace(result.ArtifactPath); artifact != "" {
		lines = append(lines, "full_output: "+artifact)
		lines = append(lines, "explore: tail -100 "+artifact)
	}
	if noisy := noisyPathSummary(output, 8); len(noisy) > 0 {
		lines = append(lines, "noisy_paths_omitted:")
		for _, path := range noisy {
			lines = append(lines, "- "+path)
		}
	}
	if head := compactCommandInterestingHead(output, 8); len(head) > 0 {
		lines = append(lines, "sample:")
		for _, line := range head {
			lines = append(lines, "  "+line)
		}
	}
	return truncateMiddle(strings.Join(lines, "\n"), limit), true
}

func commandLooksLikeGitStatus(command string) bool {
	fields := strings.Fields(command)
	return len(fields) >= 2 && fields[0] == "git" && fields[1] == "status"
}

func compactGitStatusOutput(result tools.ToolResult, limit int) string {
	output := strings.TrimSpace(strings.ReplaceAll(result.Output, "\r\n", "\n"))
	statusLines := gitStatusHeaderLines(output, 8)
	roots, noisy := gitStatusPathSummaries(output, 16)
	var lines []string
	lines = append(lines, "git status output compacted")
	if result.Truncated {
		lines = append(lines, "truncated: true")
	}
	if artifact := strings.TrimSpace(result.ArtifactPath); artifact != "" {
		lines = append(lines, "full_output: "+artifact)
		lines = append(lines, "explore: tail -100 "+artifact)
	}
	if len(statusLines) > 0 {
		lines = append(lines, "status:")
		for _, line := range statusLines {
			lines = append(lines, "  "+line)
		}
	}
	if len(roots) > 0 {
		lines = append(lines, "changed_or_untracked_roots:")
		for _, root := range roots {
			lines = append(lines, "- "+root)
		}
	}
	if len(noisy) > 0 {
		lines = append(lines, "noisy_subtrees_omitted:")
		for _, root := range noisy {
			lines = append(lines, "- "+root)
		}
	}
	return truncateMiddle(strings.Join(lines, "\n"), limit)
}

func gitStatusHeaderLines(output string, maxLines int) []string {
	var lines []string
	for _, line := range strings.Split(output, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		if _, ok := gitStatusPathFromLine(line); ok {
			continue
		}
		if strings.HasPrefix(trimmed, "(") || strings.HasPrefix(trimmed, "--- output truncated") || strings.HasPrefix(trimmed, "Full output:") || strings.HasPrefix(trimmed, "Explore:") || strings.HasPrefix(trimmed, "[exit:") {
			continue
		}
		lines = append(lines, trimmed)
		if len(lines) >= maxLines {
			break
		}
	}
	return lines
}

func gitStatusPathSummaries(output string, limit int) ([]string, []string) {
	rootsSeen := map[string]bool{}
	noisySeen := map[string]bool{}
	var roots []string
	var noisy []string
	for _, line := range strings.Split(output, "\n") {
		path, ok := gitStatusPathFromLine(line)
		if !ok {
			continue
		}
		root, noisyRoot, isNoisy := compactPathRoot(path)
		if isNoisy {
			if !noisySeen[noisyRoot] && len(noisy) < limit {
				noisySeen[noisyRoot] = true
				noisy = append(noisy, noisyRoot)
			}
			root = parentPathRoot(noisyRoot)
		}
		if root != "" && !rootsSeen[root] && len(roots) < limit {
			rootsSeen[root] = true
			roots = append(roots, root)
		}
	}
	return roots, noisy
}

func gitStatusPathFromLine(line string) (string, bool) {
	raw := strings.TrimSpace(line)
	if raw == "" || strings.HasPrefix(raw, "(") || strings.HasPrefix(raw, "On branch ") || strings.HasPrefix(raw, "Your branch ") {
		return "", false
	}
	if strings.HasPrefix(raw, "?? ") || strings.HasPrefix(raw, "A  ") || strings.HasPrefix(raw, "M  ") || strings.HasPrefix(raw, "D  ") || strings.HasPrefix(raw, "R  ") || strings.HasPrefix(raw, "C  ") {
		raw = strings.TrimSpace(raw[3:])
	} else if strings.HasPrefix(line, "\t") {
		raw = strings.TrimSpace(line)
	} else {
		return "", false
	}
	raw = strings.Trim(raw, `"`)
	if raw == "" || strings.HasSuffix(raw, ":") {
		return "", false
	}
	return filepathSlash(raw), true
}

func compactPathRoot(path string) (root, noisyRoot string, noisy bool) {
	path = filepathSlash(path)
	parts := strings.Split(path, "/")
	for i, part := range parts {
		if noisyPathSegment(part) {
			rootEnd := i
			if rootEnd < 1 {
				rootEnd = 1
			}
			return joinPathParts(parts[:rootEnd]), joinPathParts(parts[:i+1]) + "/", true
		}
	}
	if len(parts) >= 2 {
		return joinPathParts(parts[:2]) + "/", "", false
	}
	if len(parts) == 1 {
		return parts[0], "", false
	}
	return "", "", false
}

func parentPathRoot(path string) string {
	path = strings.TrimSuffix(filepathSlash(path), "/")
	if path == "" {
		return ""
	}
	parts := strings.Split(path, "/")
	if len(parts) <= 1 {
		return path
	}
	return joinPathParts(parts[:len(parts)-1]) + "/"
}

func commandOutputHasNoisyPath(output string) bool {
	return len(noisyPathSummary(output, 1)) > 0
}

func noisyPathSummary(output string, limit int) []string {
	seen := map[string]bool{}
	var out []string
	for _, line := range strings.Split(output, "\n") {
		for _, field := range strings.Fields(line) {
			_, noisyRoot, noisy := compactPathRoot(strings.Trim(field, "`'\",:;()"))
			if !noisy {
				continue
			}
			if !seen[noisyRoot] {
				seen[noisyRoot] = true
				out = append(out, noisyRoot)
				if len(out) >= limit {
					return out
				}
			}
		}
	}
	return out
}

func compactCommandInterestingHead(output string, limit int) []string {
	var out []string
	for _, line := range strings.Split(output, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.Contains(line, "/node_modules/") || strings.Contains(line, "/.git/") || strings.Contains(line, "/vendor/") {
			continue
		}
		out = append(out, line)
		if len(out) >= limit {
			return out
		}
	}
	return out
}

func noisyPathSegment(segment string) bool {
	switch strings.TrimSpace(segment) {
	case ".git", ".hg", ".svn", ".venv", "venv", "node_modules", "vendor", "dist", "build", "coverage", ".next", "out", "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache":
		return true
	default:
		return false
	}
}

func filepathSlash(path string) string {
	return strings.ReplaceAll(strings.TrimSpace(path), "\\", "/")
}

func joinPathParts(parts []string) string {
	return strings.Join(parts, "/")
}

func compactRawJSON(raw json.RawMessage, limit int) string {
	raw = []byte(strings.TrimSpace(string(raw)))
	if len(raw) == 0 {
		return "{}"
	}
	var value any
	if err := json.Unmarshal(raw, &value); err == nil {
		if encoded, err := json.Marshal(value); err == nil {
			return truncateMiddle(string(encoded), limit)
		}
	}
	return truncateMiddle(string(raw), limit)
}

func messagesApproxChars(messages []modeladapter.Message) int {
	return agentcontext.ApproxMessages(messages, func(msg modeladapter.Message) agentcontext.MessageParts {
		calls := make([]agentcontext.ToolCallParts, 0, len(msg.ToolCalls))
		for _, call := range msg.ToolCalls {
			calls = append(calls, agentcontext.ToolCallParts{
				ID:        call.ID,
				Type:      call.Type,
				Name:      call.Function.Name,
				Arguments: string(call.Function.Arguments),
			})
		}
		return agentcontext.MessageParts{
			Role:       msg.Role,
			Content:    msg.Content,
			ToolCallID: msg.ToolCallID,
			ToolCalls:  calls,
		}
	})
}

func indentBlock(text string) string {
	text = strings.TrimSpace(text)
	if text == "" {
		return "  none"
	}
	lines := strings.Split(text, "\n")
	for i, line := range lines {
		lines[i] = "  " + line
	}
	return strings.Join(lines, "\n")
}

func truncateMiddle(text string, limit int) string {
	text = strings.TrimSpace(text)
	if limit <= 0 || len(text) <= limit {
		return text
	}
	omission := fmt.Sprintf("\n... omitted %d chars ...\n", len(text)-limit)
	keep := limit - len(omission)
	if keep <= 0 {
		if limit < len(omission) {
			return omission[:limit]
		}
		return omission
	}
	runes := []rune(text)
	if len(runes) <= keep {
		return text
	}
	head := keep / 2
	tail := keep - head
	return strings.TrimSpace(string(runes[:head])) + omission + strings.TrimSpace(string(runes[len(runes)-tail:]))
}
